"use strict";
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),ui={gas:document.getElementById("gas-price"),change:document.getElementById("gas-change"),day:document.getElementById("day"),status:document.getElementById("status"),intro:document.getElementById("intro"),result:document.getElementById("result"),resultTitle:document.getElementById("result-title"),resultCopy:document.getElementById("result-copy"),ticker:document.getElementById("ticker-text"),transits:document.getElementById("transits"),losses:document.getElementById("losses"),credits:document.getElementById("credits"),store:document.getElementById("store")};
let W=0,H=0,last=0,elapsed=0,spawnClock=0,spawned=0,day=1,state="intro",gas=3.47,credits=0,campaignTransits=0,campaignLosses=0,active,missiles=[],drones=[],shots=[],blasts=[],ships=[];
const upgrades={reload:0,speed:0,radius:0,ciws:0},costs=[25,60,110],threatSpeed=1.2;
const bases=[{name:"AL UDEID",x:.10,y:.47,type:"base",day:1},{name:"AL DHAFRA",x:.37,y:.65,type:"base",day:1},{name:"USS ROOSEVELT",x:.87,y:.67,type:"ship",day:4}].map(b=>({...b,ammo:10,maxAmmo:10,disabledUntil:0,reloadUntil:0}));
const infrastructure=[{name:"OFFSHORE PLATFORMS",type:"offshore",x:.20,y:.50,hp:4,maxHp:4,destroyed:false},{name:"REFINERY",type:"refinery",x:.25,y:.75,hp:4,maxHp:4,destroyed:false}];
const sites=[{type:"missile",x:.43,y:.115,hp:2},{type:"missile",x:.61,y:.18,hp:2},{type:"missile",x:.84,y:.30,hp:2},{type:"drone",x:.36,y:.18,hp:1},{type:"drone",x:.70,y:.255,hp:1},{type:"drone",x:.91,y:.55,hp:1}].map(s=>({...s,active:false,respawn:0}));
const positions={missile:[[.34,.06],[.43,.115],[.53,.13],[.61,.18],[.70,.14],[.84,.30],[.92,.40]],drone:[[.36,.18],[.50,.285],[.62,.255],[.70,.255],[.77,.47],[.84,.50],[.91,.55]]};
const routes={east:[[.16,0],[.19,.19],[.35,.39],[.55,.42],[.65,.40],[.68,.45],[.66,.53],[.69,.72],[.77,.81],[1,.96]],west:[[1,.71],[.77,.61],[.72,.50],[.71,.37],[.66,.35],[.48,.35],[.35,.27],[.27,.17],[.25,0]]};
const landNorth=[[0,0],[.28,0],[.29,.14],[.45,.28],[.56,.30],[.68,.28],[.74,.42],[.82,.54],[1,.62],[1,0]],landSouth=[[0,0],[.11,0],[.09,.20],[.03,.47],[.23,.67],[.37,.60],[.57,.49],[.62,.43],[.58,.75],[.63,1],[0,1]];
const sx=x=>x*W,sy=y=>y*H,pick=a=>a[Math.floor(Math.random()*a.length)],availableBases=()=>bases.filter(b=>day>=b.day);
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);resize();
function sample(route,t){let total=0,l=[];for(let i=1;i<route.length;i++){total+=Math.hypot(route[i][0]-route[i-1][0],route[i][1]-route[i-1][1]);l.push(total)}let target=Math.max(0,Math.min(1,t))*total,i=0;while(l[i]<target)i++;let a=route[i]||route.at(-2),b=route[i+1]||route.at(-1),prev=i?l[i-1]:0,u=(target-prev)/((l[i]||total)-prev||1);return{x:a[0]+(b[0]-a[0])*u,y:a[1]+(b[1]-a[1])*u,a:Math.atan2((b[1]-a[1])*H,(b[0]-a[0])*W)}}
function hud(){ui.gas.textContent="$"+gas.toFixed(2);ui.credits.textContent=String(credits).padStart(3,"0");ui.day.textContent=String(day).padStart(2,"0");ui.transits.textContent=String(campaignTransits+ships.filter(s=>s.done).length).padStart(2,"0");ui.losses.textContent=String(campaignLosses+ships.filter(s=>s.hp<=0).length).padStart(2,"0");let d=gas-3.47;ui.change.textContent=(d>=0?"▲ +":"▼ -")+Math.abs(d).toFixed(2);ui.change.style.color=d>0?"#ff7138":"#9ee75b"}
function reset(){day=1;gas=3.47;credits=campaignTransits=campaignLosses=0;Object.keys(upgrades).forEach(k=>upgrades[k]=0);infrastructure.forEach(o=>{o.hp=4;o.destroyed=false});startDay()}
function startDay(){state="playing";elapsed=spawnClock=spawned=0;missiles=[];drones=[];shots=[];blasts=[];availableBases().forEach(b=>{b.ammo=b.maxAmmo;b.disabledUntil=b.reloadUntil=0});active=availableBases().at(-1);sites.forEach(s=>{s.hp=s.type==="missile"?2:1;s.active=false;s.respawn=0});ships=[{p:-.04,v:.040,r:routes.east},{p:-.20,v:.038,r:routes.east},{p:-.36,v:.036,r:routes.east},{p:-.52,v:.034,r:routes.east},{p:-.06,v:.039,r:routes.west},{p:-.30,v:.035,r:routes.west}].map(s=>({...s,hp:1,done:false,x:0,y:0,a:0}));ui.intro.classList.add("hidden");ui.result.classList.add("hidden");ui.ticker.textContent=day===4?"USS ROOSEVELT HAS ARRIVED IN THE GULF OF OMAN —":"DAY "+day+" ACTIVE — PROTECT SHIPPING AND INFRASTRUCTURE —";hud()}
function targetFor(kind){let vessels=ships.filter(s=>s.hp>0&&!s.done),targets=kind==="missile"?[...vessels,...infrastructure.filter(o=>!o.destroyed),...availableBases()]:[...vessels,...availableBases()];return targets.length?pick(targets):null}
function spawn(){if(spawned>=26)return;let kind=Math.random()<.5?"missile":"drone",pool=sites.filter(s=>s.type===kind&&s.hp>0);if(!pool.length){kind=kind==="missile"?"drone":"missile";pool=sites.filter(s=>s.type===kind&&s.hp>0)}let target=targetFor(kind);if(!pool.length||!target)return;let site=pick(pool),x=sx(site.x),y=sy(site.y),tx=sx(target.x),ty=sy(target.y),speed=(kind==="missile"?105:70)*threatSpeed,t={kind,site,target,x,y,sx:x,sy:y,tx,ty,age:0,duration:Math.hypot(tx-x,ty-y)/speed,dead:false};site.active=true;spawned++;(kind==="missile"?missiles:drones).push(t)}
function explode(x,y,r=75){blasts.push({x,y,r:2,max:r,age:0});}
function hit(t){explode(t.x,t.y,45);let target=t.target;if(!target)return;if(target.maxHp===4){target.hp--;gas=Math.min(7.99,gas+.22);if(target.hp<=0){target.hp=0;target.destroyed=true;gas=Math.min(7.99,gas+.35);ui.ticker.textContent=target.name+" DESTROYED — DAMAGE IS PERMANENT —"}}else if(target.type==="base"||target.type==="ship"){target.disabledUntil=elapsed+2;ui.status.textContent=target.name+" DISABLED 2.0s"}else{target.hp--;gas=Math.min(7.99,gas+.18)}hud()}
function launch(x,y){if(state!=="playing")return;let clicked=availableBases().find(b=>Math.hypot(sx(b.x)-x,sy(b.y)-y)<32);if(clicked){if(clicked!==active){active=clicked;ui.status.textContent=clicked.name+" ACTIVE"}else if(!clicked.reloadUntil&&clicked.ammo<clicked.maxAmmo)clicked.reloadUntil=elapsed+[4,3.2,2.5,1.8][upgrades.reload];return}if(active.disabledUntil>elapsed||active.reloadUntil||active.ammo<=0)return;active.ammo--;shots.push({x:sx(active.x),y:sy(active.y),tx:x,ty:y,speed:[620,730,850,980][upgrades.speed],dead:false});hud()}
function update(dt){if(state!=="playing")return;elapsed+=dt;spawnClock+=dt;availableBases().forEach(b=>{if(b.reloadUntil&&elapsed>=b.reloadUntil){b.ammo=b.maxAmmo;b.reloadUntil=0}});sites.forEach(s=>{if(s.respawn&&elapsed>=s.respawn){let p=pick(positions[s.type]);s.x=p[0];s.y=p[1];s.hp=s.type==="missile"?2:1;s.respawn=0;s.active=false}});if(spawned<26&&spawnClock>Math.max(.55,2.45-(day-1)*.18-elapsed*.004)){spawnClock=0;spawn()}ships.forEach(s=>{if(s.hp>0&&!s.done){s.p+=s.v*dt;let p=sample(s.r,s.p);Object.assign(s,p);if(s.p>1){s.done=true;gas=Math.max(1.5,gas-.14);credits+=3;hud()}}});shots.forEach(s=>{let dx=s.tx-s.x,dy=s.ty-s.y,d=Math.hypot(dx,dy);if(d<s.speed*dt){s.dead=true;explode(s.tx,s.ty,[74,86,100,116][upgrades.radius])}else{s.x+=dx/d*s.speed*dt;s.y+=dy/d*s.speed*dt}});[...missiles,...drones].forEach(t=>{if(t.kind==="drone"){t.tx=sx(t.target.x);t.ty=sy(t.target.y)}t.age+=dt;let p=Math.min(1,t.age/t.duration);t.x=t.sx+(t.tx-t.sx)*p;t.y=t.sy+(t.ty-t.sy)*p-(t.kind==="missile"?Math.sin(p*Math.PI)*H*.22:0);if(p>=1){t.dead=true;hit(t)}});if(day>=4&&upgrades.ciws){let r=bases[2],d=drones.find(t=>!t.dead&&Math.hypot(t.x-sx(r.x),t.y-sy(r.y))<Math.min(W,H)*.16);if(d){d.dead=true;explode(d.x,d.y,25)}}blasts.forEach(b=>{b.age+=dt;b.r=Math.sin(Math.min(1,b.age/1.1)*Math.PI)*b.max;if(b.age>1.1)b.dead=true;[...missiles,...drones].forEach(t=>{if(!t.dead&&Math.hypot(t.x-b.x,t.y-b.y)<b.r){t.dead=true;credits+=1}});sites.forEach(s=>{if(s.hp>0&&Math.hypot(sx(s.x)-b.x,sy(s.y)-b.y)<b.r){s.hp--;if(s.hp<=0){s.active=false;s.respawn=elapsed+3;credits+=5}}})});missiles=missiles.filter(t=>!t.dead);drones=drones.filter(t=>!t.dead);shots=shots.filter(t=>!t.dead);blasts=blasts.filter(t=>!t.dead);if(ships.every(s=>s.done||s.hp<=0))finish()}
function store(){ui.store.innerHTML="";let names={reload:"FASTER RELOAD",speed:"FASTER U.S. MISSILES",radius:"LARGER EXPLOSION"};Object.keys(names).forEach(k=>{let l=upgrades[k],b=document.createElement("button");b.className="upgrade";b.disabled=l>=3;b.innerHTML=`<strong>${names[k]}</strong><span>LEVEL ${l} / 3</span><small>${l>=3?"MAXIMUM":costs[l]+" CR"}</small>`;b.onclick=()=>{if(credits>=costs[l]){credits-=costs[l];upgrades[k]++;hud();store()}};ui.store.appendChild(b)});if(day>=4){let b=document.createElement("button");b.className="upgrade";b.disabled=!!upgrades.ciws;b.innerHTML=`<strong>ROOSEVELT CIWS</strong><span>DRONE SELF-DEFENSE</span><small>${upgrades.ciws?"INSTALLED":"55 CR"}</small>`;b.onclick=()=>{if(credits>=55&&!upgrades.ciws){credits-=55;upgrades.ciws=1;hud();store()}};ui.store.appendChild(b)}}
function finish(){state="result";let saved=ships.filter(s=>s.done).length,lost=ships.filter(s=>s.hp<=0).length;campaignTransits+=saved;campaignLosses+=lost;ui.resultTitle.textContent=gas>5?"GAME OVER":"DAY "+day+" COMPLETE";ui.resultCopy.textContent=`${saved} vessels cleared · ${lost} lost · ${credits} credits available`;ui.store.classList.toggle("hidden",gas>5);if(gas<=5)store();ui.result.classList.remove("hidden");let b=document.getElementById("restart");b.dataset.action=gas>5?"restart":"next";b.textContent=gas>5?"RESTART CAMPAIGN":"CONTINUE TO DAY "+(day+1);hud()}
function poly(p,fill,stroke){ctx.beginPath();p.forEach((q,i)=>i?ctx.lineTo(...q):ctx.moveTo(...q));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function draw(){ctx.fillStyle="#092719";ctx.fillRect(0,0,W,H);poly(landNorth.map(([x,y])=>[sx(x),sy(y)]),"#172d15","#a8d93c");poly(landSouth.map(([x,y])=>[sx(x),sy(y)]),"#183016","#a8d93c");infrastructure.forEach(o=>{ctx.save();ctx.translate(sx(o.x),sy(o.y));ctx.strokeStyle=o.destroyed?"#69331f":"#d8c849";if(o.type==="offshore")[-14,0,14].forEach(x=>ctx.strokeRect(x-6,-8,12,14));else{ctx.strokeRect(-18,-5,36,10);ctx.strokeRect(8,-28,7,23);ctx.beginPath();ctx.arc(-8,-10,9,Math.PI,0);ctx.stroke()}ctx.fillStyle="#d8c849";ctx.font="10px monospace";ctx.textAlign="center";ctx.fillText(o.destroyed?"DESTROYED":"HP "+o.hp+"/4",0,22);ctx.restore()});ships.forEach(s=>{if(s.done||s.hp<=0)return;ctx.save();ctx.translate(sx(s.x),sy(s.y));ctx.rotate(s.a);poly([[-25,-5],[22,-5],[30,0],[20,6],[-25,6]],"#18331b","#b7e34b");ctx.restore()});availableBases().forEach(b=>{ctx.save();ctx.translate(sx(b.x),sy(b.y));ctx.strokeStyle=b===active?"#fff27a":"#d8c849";if(b.type==="ship")poly([[-32,-6],[25,-6],[35,0],[23,7],[-29,7]],"#20351b",ctx.strokeStyle);else{[-13,13].forEach((x,i)=>{ctx.strokeRect(x-9,-5,18,10);ctx.beginPath();ctx.moveTo(x+(i?-5:5),-7);ctx.lineTo(x+(i?7:-7),-22);ctx.stroke()});ctx.beginPath();ctx.arc(0,-8,7,0,7);ctx.stroke()}ctx.fillStyle=ctx.strokeStyle;ctx.font="10px monospace";ctx.textAlign="center";ctx.fillText(b.name,0,23);ctx.restore()});sites.forEach(s=>{if(!s.active)return;ctx.save();ctx.translate(sx(s.x),sy(s.y));ctx.strokeStyle="#f06d3d";ctx.strokeRect(-14,-5,28,10);if(s.type==="missile"){ctx.save();ctx.rotate(-Math.PI/4);ctx.strokeRect(0,-3,25,6);ctx.restore()}else ctx.strokeRect(5,-12,9,7);ctx.restore()});[...missiles,...drones].forEach(t=>{ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle="#ff8a55";poly(t.kind==="drone"?[[12,0],[-3,-7],[-15,-4],[-6,0],[-15,4],[-3,7]]:[[14,0],[8,-3],[-10,-3],[-15,0],[-10,3],[8,3]],ctx.fillStyle,"#ffd79a");ctx.restore()});shots.forEach(s=>{ctx.fillStyle="#fff";ctx.fillRect(s.x-2,s.y-2,4,4)});blasts.forEach(b=>{ctx.strokeStyle="#b8fff0";ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.stroke()})}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
canvas.addEventListener("pointerdown",e=>{let r=canvas.getBoundingClientRect();launch(e.clientX-r.left,e.clientY-r.top)});document.getElementById("start").onclick=reset;ui.intro.onclick=e=>{if(e.target.id!=="start")reset()};document.getElementById("restart").onclick=e=>{if(e.currentTarget.dataset.action==="next"){day++;startDay()}else reset()};